server:
  port: 8081

crud.wizard:
  metamodel:
      datasource:
        url: jdbc:postgresql://localhost:5432/simple-metamodel
        driverClassName: org.postgresql.Driver
        username: postgres
        password: postgres

  jdbc-data-storage:
    datasource:
      url: jdbc:postgresql://localhost:5432/simple-application
      driverClassName: org.postgresql.Driver
      username: postgres
      password: postgres

spring:
  jpa:
    database-platform: #empty (detected at runtime) do not remove this line
    open-in-view: false
    properties:
      hibernate:
        hbm2ddl.auto: update # validate
        jdbc.lob.non_contextual_creation: true
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
